// Generated by gencpp from file ros_mscl/DeviceSettingsRequest.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_DEVICESETTINGSREQUEST_H
#define ROS_MSCL_MESSAGE_DEVICESETTINGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct DeviceSettingsRequest_
{
  typedef DeviceSettingsRequest_<ContainerAllocator> Type;

  DeviceSettingsRequest_()
    : function_selector(0)  {
    }
  DeviceSettingsRequest_(const ContainerAllocator& _alloc)
    : function_selector(0)  {
  (void)_alloc;
    }



   typedef uint8_t _function_selector_type;
  _function_selector_type function_selector;





  typedef boost::shared_ptr< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceSettingsRequest_

typedef ::ros_mscl::DeviceSettingsRequest_<std::allocator<void> > DeviceSettingsRequest;

typedef boost::shared_ptr< ::ros_mscl::DeviceSettingsRequest > DeviceSettingsRequestPtr;
typedef boost::shared_ptr< ::ros_mscl::DeviceSettingsRequest const> DeviceSettingsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.function_selector == rhs.function_selector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8af3ea6ac2cd14406fd4b4301d1878d2";
  }

  static const char* value(const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8af3ea6ac2cd1440ULL;
  static const uint64_t static_value2 = 0x6fd4b4301d1878d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/DeviceSettingsRequest";
  }

  static const char* value(const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 function_selector\n"
;
  }

  static const char* value(const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.function_selector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceSettingsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::DeviceSettingsRequest_<ContainerAllocator>& v)
  {
    s << indent << "function_selector: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.function_selector);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_DEVICESETTINGSREQUEST_H
