// Generated by gencpp from file ros_mscl/DeviceSettings.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_DEVICESETTINGS_H
#define ROS_MSCL_MESSAGE_DEVICESETTINGS_H

#include <ros/service_traits.h>


#include <ros_mscl/DeviceSettingsRequest.h>
#include <ros_mscl/DeviceSettingsResponse.h>


namespace ros_mscl
{

struct DeviceSettings
{

typedef DeviceSettingsRequest Request;
typedef DeviceSettingsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeviceSettings
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::DeviceSettings > {
  static const char* value()
  {
    return "a5738bbd08ff2569a7464cd41b071fc3";
  }

  static const char* value(const ::ros_mscl::DeviceSettings&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::DeviceSettings > {
  static const char* value()
  {
    return "ros_mscl/DeviceSettings";
  }

  static const char* value(const ::ros_mscl::DeviceSettings&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::DeviceSettingsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::DeviceSettings >
template<>
struct MD5Sum< ::ros_mscl::DeviceSettingsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::DeviceSettings >::value();
  }
  static const char* value(const ::ros_mscl::DeviceSettingsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::DeviceSettingsRequest> should match
// service_traits::DataType< ::ros_mscl::DeviceSettings >
template<>
struct DataType< ::ros_mscl::DeviceSettingsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::DeviceSettings >::value();
  }
  static const char* value(const ::ros_mscl::DeviceSettingsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::DeviceSettingsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::DeviceSettings >
template<>
struct MD5Sum< ::ros_mscl::DeviceSettingsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::DeviceSettings >::value();
  }
  static const char* value(const ::ros_mscl::DeviceSettingsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::DeviceSettingsResponse> should match
// service_traits::DataType< ::ros_mscl::DeviceSettings >
template<>
struct DataType< ::ros_mscl::DeviceSettingsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::DeviceSettings >::value();
  }
  static const char* value(const ::ros_mscl::DeviceSettingsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_DEVICESETTINGS_H
