// Generated by gencpp from file ros_mscl/ExternalHeadingUpdate.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_EXTERNALHEADINGUPDATE_H
#define ROS_MSCL_MESSAGE_EXTERNALHEADINGUPDATE_H

#include <ros/service_traits.h>


#include <ros_mscl/ExternalHeadingUpdateRequest.h>
#include <ros_mscl/ExternalHeadingUpdateResponse.h>


namespace ros_mscl
{

struct ExternalHeadingUpdate
{

typedef ExternalHeadingUpdateRequest Request;
typedef ExternalHeadingUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExternalHeadingUpdate
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::ExternalHeadingUpdate > {
  static const char* value()
  {
    return "c947f180cef8662c7c56b8c41afcba62";
  }

  static const char* value(const ::ros_mscl::ExternalHeadingUpdate&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::ExternalHeadingUpdate > {
  static const char* value()
  {
    return "ros_mscl/ExternalHeadingUpdate";
  }

  static const char* value(const ::ros_mscl::ExternalHeadingUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::ExternalHeadingUpdateRequest> should match
// service_traits::MD5Sum< ::ros_mscl::ExternalHeadingUpdate >
template<>
struct MD5Sum< ::ros_mscl::ExternalHeadingUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::ExternalHeadingUpdate >::value();
  }
  static const char* value(const ::ros_mscl::ExternalHeadingUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::ExternalHeadingUpdateRequest> should match
// service_traits::DataType< ::ros_mscl::ExternalHeadingUpdate >
template<>
struct DataType< ::ros_mscl::ExternalHeadingUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::ExternalHeadingUpdate >::value();
  }
  static const char* value(const ::ros_mscl::ExternalHeadingUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::ExternalHeadingUpdateResponse> should match
// service_traits::MD5Sum< ::ros_mscl::ExternalHeadingUpdate >
template<>
struct MD5Sum< ::ros_mscl::ExternalHeadingUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::ExternalHeadingUpdate >::value();
  }
  static const char* value(const ::ros_mscl::ExternalHeadingUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::ExternalHeadingUpdateResponse> should match
// service_traits::DataType< ::ros_mscl::ExternalHeadingUpdate >
template<>
struct DataType< ::ros_mscl::ExternalHeadingUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::ExternalHeadingUpdate >::value();
  }
  static const char* value(const ::ros_mscl::ExternalHeadingUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_EXTERNALHEADINGUPDATE_H
