// Generated by gencpp from file ros_mscl/GetAccelAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETACCELADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_GETACCELADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/GetAccelAdaptiveValsRequest.h>
#include <ros_mscl/GetAccelAdaptiveValsResponse.h>


namespace ros_mscl
{

struct GetAccelAdaptiveVals
{

typedef GetAccelAdaptiveValsRequest Request;
typedef GetAccelAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAccelAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetAccelAdaptiveVals > {
  static const char* value()
  {
    return "88594dfd6d7363edbe6f8e16638532cc";
  }

  static const char* value(const ::ros_mscl::GetAccelAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetAccelAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/GetAccelAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::GetAccelAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetAccelAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetAccelAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetAccelAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetAccelAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetAccelAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::GetAccelAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetAccelAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetAccelAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetAccelAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetAccelAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetAccelAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetAccelAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetAccelAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::GetAccelAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetAccelAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetAccelAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETACCELADAPTIVEVALS_H
