// Generated by gencpp from file ros_mscl/GetAccelNoiseResponse.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETACCELNOISERESPONSE_H
#define ROS_MSCL_MESSAGE_GETACCELNOISERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace ros_mscl
{
template <class ContainerAllocator>
struct GetAccelNoiseResponse_
{
  typedef GetAccelNoiseResponse_<ContainerAllocator> Type;

  GetAccelNoiseResponse_()
    : noise()
    , success(false)  {
    }
  GetAccelNoiseResponse_(const ContainerAllocator& _alloc)
    : noise(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _noise_type;
  _noise_type noise;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAccelNoiseResponse_

typedef ::ros_mscl::GetAccelNoiseResponse_<std::allocator<void> > GetAccelNoiseResponse;

typedef boost::shared_ptr< ::ros_mscl::GetAccelNoiseResponse > GetAccelNoiseResponsePtr;
typedef boost::shared_ptr< ::ros_mscl::GetAccelNoiseResponse const> GetAccelNoiseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.noise == rhs.noise &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f98ca1a5e4f9d504cd0b08eeeda072c5";
  }

  static const char* value(const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf98ca1a5e4f9d504ULL;
  static const uint64_t static_value2 = 0xcd0b08eeeda072c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/GetAccelNoiseResponse";
  }

  static const char* value(const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 noise\n"
"bool success\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.noise);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAccelNoiseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::GetAccelNoiseResponse_<ContainerAllocator>& v)
  {
    s << indent << "noise: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.noise);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETACCELNOISERESPONSE_H
