// Generated by gencpp from file ros_mscl/GetComplementaryFilter.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETCOMPLEMENTARYFILTER_H
#define ROS_MSCL_MESSAGE_GETCOMPLEMENTARYFILTER_H

#include <ros/service_traits.h>


#include <ros_mscl/GetComplementaryFilterRequest.h>
#include <ros_mscl/GetComplementaryFilterResponse.h>


namespace ros_mscl
{

struct GetComplementaryFilter
{

typedef GetComplementaryFilterRequest Request;
typedef GetComplementaryFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetComplementaryFilter
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetComplementaryFilter > {
  static const char* value()
  {
    return "182da770aa33d31e1eeca2d1e7ed5c19";
  }

  static const char* value(const ::ros_mscl::GetComplementaryFilter&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetComplementaryFilter > {
  static const char* value()
  {
    return "ros_mscl/GetComplementaryFilter";
  }

  static const char* value(const ::ros_mscl::GetComplementaryFilter&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetComplementaryFilterRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetComplementaryFilter >
template<>
struct MD5Sum< ::ros_mscl::GetComplementaryFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetComplementaryFilter >::value();
  }
  static const char* value(const ::ros_mscl::GetComplementaryFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetComplementaryFilterRequest> should match
// service_traits::DataType< ::ros_mscl::GetComplementaryFilter >
template<>
struct DataType< ::ros_mscl::GetComplementaryFilterRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetComplementaryFilter >::value();
  }
  static const char* value(const ::ros_mscl::GetComplementaryFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetComplementaryFilterResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetComplementaryFilter >
template<>
struct MD5Sum< ::ros_mscl::GetComplementaryFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetComplementaryFilter >::value();
  }
  static const char* value(const ::ros_mscl::GetComplementaryFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetComplementaryFilterResponse> should match
// service_traits::DataType< ::ros_mscl::GetComplementaryFilter >
template<>
struct DataType< ::ros_mscl::GetComplementaryFilterResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetComplementaryFilter >::value();
  }
  static const char* value(const ::ros_mscl::GetComplementaryFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETCOMPLEMENTARYFILTER_H
