// Generated by gencpp from file ros_mscl/GetConingScullingCompResponse.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMPRESPONSE_H
#define ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct GetConingScullingCompResponse_
{
  typedef GetConingScullingCompResponse_<ContainerAllocator> Type;

  GetConingScullingCompResponse_()
    : enable(0)
    , success(false)  {
    }
  GetConingScullingCompResponse_(const ContainerAllocator& _alloc)
    : enable(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int8_t _enable_type;
  _enable_type enable;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetConingScullingCompResponse_

typedef ::ros_mscl::GetConingScullingCompResponse_<std::allocator<void> > GetConingScullingCompResponse;

typedef boost::shared_ptr< ::ros_mscl::GetConingScullingCompResponse > GetConingScullingCompResponsePtr;
typedef boost::shared_ptr< ::ros_mscl::GetConingScullingCompResponse const> GetConingScullingCompResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73ec157fb12f6cbfec05839300a44bb3";
  }

  static const char* value(const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73ec157fb12f6cbfULL;
  static const uint64_t static_value2 = 0xec05839300a44bb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/GetConingScullingCompResponse";
  }

  static const char* value(const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enable\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetConingScullingCompResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::GetConingScullingCompResponse_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMPRESPONSE_H
