// Generated by gencpp from file ros_mscl/GetConingScullingComp.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMP_H
#define ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMP_H

#include <ros/service_traits.h>


#include <ros_mscl/GetConingScullingCompRequest.h>
#include <ros_mscl/GetConingScullingCompResponse.h>


namespace ros_mscl
{

struct GetConingScullingComp
{

typedef GetConingScullingCompRequest Request;
typedef GetConingScullingCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetConingScullingComp
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetConingScullingComp > {
  static const char* value()
  {
    return "73ec157fb12f6cbfec05839300a44bb3";
  }

  static const char* value(const ::ros_mscl::GetConingScullingComp&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetConingScullingComp > {
  static const char* value()
  {
    return "ros_mscl/GetConingScullingComp";
  }

  static const char* value(const ::ros_mscl::GetConingScullingComp&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetConingScullingCompRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetConingScullingComp >
template<>
struct MD5Sum< ::ros_mscl::GetConingScullingCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::GetConingScullingCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetConingScullingCompRequest> should match
// service_traits::DataType< ::ros_mscl::GetConingScullingComp >
template<>
struct DataType< ::ros_mscl::GetConingScullingCompRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::GetConingScullingCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetConingScullingCompResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetConingScullingComp >
template<>
struct MD5Sum< ::ros_mscl::GetConingScullingCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::GetConingScullingCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetConingScullingCompResponse> should match
// service_traits::DataType< ::ros_mscl::GetConingScullingComp >
template<>
struct DataType< ::ros_mscl::GetConingScullingCompResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::GetConingScullingCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETCONINGSCULLINGCOMP_H
