// Generated by gencpp from file ros_mscl/GetEstimationControlFlags.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETESTIMATIONCONTROLFLAGS_H
#define ROS_MSCL_MESSAGE_GETESTIMATIONCONTROLFLAGS_H

#include <ros/service_traits.h>


#include <ros_mscl/GetEstimationControlFlagsRequest.h>
#include <ros_mscl/GetEstimationControlFlagsResponse.h>


namespace ros_mscl
{

struct GetEstimationControlFlags
{

typedef GetEstimationControlFlagsRequest Request;
typedef GetEstimationControlFlagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEstimationControlFlags
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetEstimationControlFlags > {
  static const char* value()
  {
    return "20bb471857675e9f69991d48317a4755";
  }

  static const char* value(const ::ros_mscl::GetEstimationControlFlags&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetEstimationControlFlags > {
  static const char* value()
  {
    return "ros_mscl/GetEstimationControlFlags";
  }

  static const char* value(const ::ros_mscl::GetEstimationControlFlags&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetEstimationControlFlagsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetEstimationControlFlags >
template<>
struct MD5Sum< ::ros_mscl::GetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::GetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetEstimationControlFlagsRequest> should match
// service_traits::DataType< ::ros_mscl::GetEstimationControlFlags >
template<>
struct DataType< ::ros_mscl::GetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::GetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetEstimationControlFlagsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetEstimationControlFlags >
template<>
struct MD5Sum< ::ros_mscl::GetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::GetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetEstimationControlFlagsResponse> should match
// service_traits::DataType< ::ros_mscl::GetEstimationControlFlags >
template<>
struct DataType< ::ros_mscl::GetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::GetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETESTIMATIONCONTROLFLAGS_H
