// Generated by gencpp from file ros_mscl/GetGyroBias.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETGYROBIAS_H
#define ROS_MSCL_MESSAGE_GETGYROBIAS_H

#include <ros/service_traits.h>


#include <ros_mscl/GetGyroBiasRequest.h>
#include <ros_mscl/GetGyroBiasResponse.h>


namespace ros_mscl
{

struct GetGyroBias
{

typedef GetGyroBiasRequest Request;
typedef GetGyroBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGyroBias
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetGyroBias > {
  static const char* value()
  {
    return "9427c94a8464f80e7ccfb4c788698d94";
  }

  static const char* value(const ::ros_mscl::GetGyroBias&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetGyroBias > {
  static const char* value()
  {
    return "ros_mscl/GetGyroBias";
  }

  static const char* value(const ::ros_mscl::GetGyroBias&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetGyroBiasRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetGyroBias >
template<>
struct MD5Sum< ::ros_mscl::GetGyroBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetGyroBiasRequest> should match
// service_traits::DataType< ::ros_mscl::GetGyroBias >
template<>
struct DataType< ::ros_mscl::GetGyroBiasRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetGyroBiasResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetGyroBias >
template<>
struct MD5Sum< ::ros_mscl::GetGyroBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetGyroBiasResponse> should match
// service_traits::DataType< ::ros_mscl::GetGyroBias >
template<>
struct DataType< ::ros_mscl::GetGyroBiasResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETGYROBIAS_H
