// Generated by gencpp from file ros_mscl/GetGyroNoise.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETGYRONOISE_H
#define ROS_MSCL_MESSAGE_GETGYRONOISE_H

#include <ros/service_traits.h>


#include <ros_mscl/GetGyroNoiseRequest.h>
#include <ros_mscl/GetGyroNoiseResponse.h>


namespace ros_mscl
{

struct GetGyroNoise
{

typedef GetGyroNoiseRequest Request;
typedef GetGyroNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGyroNoise
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetGyroNoise > {
  static const char* value()
  {
    return "f98ca1a5e4f9d504cd0b08eeeda072c5";
  }

  static const char* value(const ::ros_mscl::GetGyroNoise&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetGyroNoise > {
  static const char* value()
  {
    return "ros_mscl/GetGyroNoise";
  }

  static const char* value(const ::ros_mscl::GetGyroNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetGyroNoiseRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetGyroNoise >
template<>
struct MD5Sum< ::ros_mscl::GetGyroNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetGyroNoiseRequest> should match
// service_traits::DataType< ::ros_mscl::GetGyroNoise >
template<>
struct DataType< ::ros_mscl::GetGyroNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetGyroNoiseResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetGyroNoise >
template<>
struct MD5Sum< ::ros_mscl::GetGyroNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetGyroNoiseResponse> should match
// service_traits::DataType< ::ros_mscl::GetGyroNoise >
template<>
struct DataType< ::ros_mscl::GetGyroNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetGyroNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETGYRONOISE_H
