// Generated by gencpp from file ros_mscl/GetHeadingSource.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETHEADINGSOURCE_H
#define ROS_MSCL_MESSAGE_GETHEADINGSOURCE_H

#include <ros/service_traits.h>


#include <ros_mscl/GetHeadingSourceRequest.h>
#include <ros_mscl/GetHeadingSourceResponse.h>


namespace ros_mscl
{

struct GetHeadingSource
{

typedef GetHeadingSourceRequest Request;
typedef GetHeadingSourceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHeadingSource
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetHeadingSource > {
  static const char* value()
  {
    return "ca422f921c27e7defb38d013092d0d4f";
  }

  static const char* value(const ::ros_mscl::GetHeadingSource&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetHeadingSource > {
  static const char* value()
  {
    return "ros_mscl/GetHeadingSource";
  }

  static const char* value(const ::ros_mscl::GetHeadingSource&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetHeadingSourceRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetHeadingSource >
template<>
struct MD5Sum< ::ros_mscl::GetHeadingSourceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::GetHeadingSourceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetHeadingSourceRequest> should match
// service_traits::DataType< ::ros_mscl::GetHeadingSource >
template<>
struct DataType< ::ros_mscl::GetHeadingSourceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::GetHeadingSourceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetHeadingSourceResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetHeadingSource >
template<>
struct MD5Sum< ::ros_mscl::GetHeadingSourceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::GetHeadingSourceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetHeadingSourceResponse> should match
// service_traits::DataType< ::ros_mscl::GetHeadingSource >
template<>
struct DataType< ::ros_mscl::GetHeadingSourceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::GetHeadingSourceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETHEADINGSOURCE_H
