// Generated by gencpp from file ros_mscl/GetHardIronValues.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETHARDIRONVALUES_H
#define ROS_MSCL_MESSAGE_GETHARDIRONVALUES_H

#include <ros/service_traits.h>


#include <ros_mscl/GetHardIronValuesRequest.h>
#include <ros_mscl/GetHardIronValuesResponse.h>


namespace ros_mscl
{

struct GetHardIronValues
{

typedef GetHardIronValuesRequest Request;
typedef GetHardIronValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHardIronValues
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetHardIronValues > {
  static const char* value()
  {
    return "9427c94a8464f80e7ccfb4c788698d94";
  }

  static const char* value(const ::ros_mscl::GetHardIronValues&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetHardIronValues > {
  static const char* value()
  {
    return "ros_mscl/GetHardIronValues";
  }

  static const char* value(const ::ros_mscl::GetHardIronValues&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetHardIronValuesRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetHardIronValues >
template<>
struct MD5Sum< ::ros_mscl::GetHardIronValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::GetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetHardIronValuesRequest> should match
// service_traits::DataType< ::ros_mscl::GetHardIronValues >
template<>
struct DataType< ::ros_mscl::GetHardIronValuesRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::GetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetHardIronValuesResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetHardIronValues >
template<>
struct MD5Sum< ::ros_mscl::GetHardIronValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::GetHardIronValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetHardIronValuesResponse> should match
// service_traits::DataType< ::ros_mscl::GetHardIronValues >
template<>
struct DataType< ::ros_mscl::GetHardIronValuesResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::GetHardIronValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETHARDIRONVALUES_H
