// Generated by gencpp from file ros_mscl/GetMagNoise.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETMAGNOISE_H
#define ROS_MSCL_MESSAGE_GETMAGNOISE_H

#include <ros/service_traits.h>


#include <ros_mscl/GetMagNoiseRequest.h>
#include <ros_mscl/GetMagNoiseResponse.h>


namespace ros_mscl
{

struct GetMagNoise
{

typedef GetMagNoiseRequest Request;
typedef GetMagNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMagNoise
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetMagNoise > {
  static const char* value()
  {
    return "f98ca1a5e4f9d504cd0b08eeeda072c5";
  }

  static const char* value(const ::ros_mscl::GetMagNoise&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetMagNoise > {
  static const char* value()
  {
    return "ros_mscl/GetMagNoise";
  }

  static const char* value(const ::ros_mscl::GetMagNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetMagNoiseRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagNoise >
template<>
struct MD5Sum< ::ros_mscl::GetMagNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagNoiseRequest> should match
// service_traits::DataType< ::ros_mscl::GetMagNoise >
template<>
struct DataType< ::ros_mscl::GetMagNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetMagNoiseResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagNoise >
template<>
struct MD5Sum< ::ros_mscl::GetMagNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetMagNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagNoiseResponse> should match
// service_traits::DataType< ::ros_mscl::GetMagNoise >
template<>
struct DataType< ::ros_mscl::GetMagNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::GetMagNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETMAGNOISE_H
