// Generated by gencpp from file ros_mscl/GetMagDipAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETMAGDIPADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_GETMAGDIPADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/GetMagDipAdaptiveValsRequest.h>
#include <ros_mscl/GetMagDipAdaptiveValsResponse.h>


namespace ros_mscl
{

struct GetMagDipAdaptiveVals
{

typedef GetMagDipAdaptiveValsRequest Request;
typedef GetMagDipAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMagDipAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "6535c8e36eb2a05d297cfae6a8a9365d";
  }

  static const char* value(const ::ros_mscl::GetMagDipAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/GetMagDipAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::GetMagDipAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetMagDipAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagDipAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::GetMagDipAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetMagDipAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagDipAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::GetMagDipAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETMAGDIPADAPTIVEVALS_H
