// Generated by gencpp from file ros_mscl/GetMagAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETMAGADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_GETMAGADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/GetMagAdaptiveValsRequest.h>
#include <ros_mscl/GetMagAdaptiveValsResponse.h>


namespace ros_mscl
{

struct GetMagAdaptiveVals
{

typedef GetMagAdaptiveValsRequest Request;
typedef GetMagAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMagAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetMagAdaptiveVals > {
  static const char* value()
  {
    return "88594dfd6d7363edbe6f8e16638532cc";
  }

  static const char* value(const ::ros_mscl::GetMagAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetMagAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/GetMagAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::GetMagAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetMagAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetMagAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::GetMagAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetMagAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetMagAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetMagAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::GetMagAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetMagAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::GetMagAdaptiveVals >
template<>
struct DataType< ::ros_mscl::GetMagAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::GetMagAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETMAGADAPTIVEVALS_H
