// Generated by gencpp from file ros_mscl/GetReferencePosition.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETREFERENCEPOSITION_H
#define ROS_MSCL_MESSAGE_GETREFERENCEPOSITION_H

#include <ros/service_traits.h>


#include <ros_mscl/GetReferencePositionRequest.h>
#include <ros_mscl/GetReferencePositionResponse.h>


namespace ros_mscl
{

struct GetReferencePosition
{

typedef GetReferencePositionRequest Request;
typedef GetReferencePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetReferencePosition
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetReferencePosition > {
  static const char* value()
  {
    return "10b5e069422b2cf203664f7c0186f64a";
  }

  static const char* value(const ::ros_mscl::GetReferencePosition&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetReferencePosition > {
  static const char* value()
  {
    return "ros_mscl/GetReferencePosition";
  }

  static const char* value(const ::ros_mscl::GetReferencePosition&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetReferencePositionRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetReferencePosition >
template<>
struct MD5Sum< ::ros_mscl::GetReferencePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::GetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetReferencePositionRequest> should match
// service_traits::DataType< ::ros_mscl::GetReferencePosition >
template<>
struct DataType< ::ros_mscl::GetReferencePositionRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::GetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetReferencePositionResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetReferencePosition >
template<>
struct MD5Sum< ::ros_mscl::GetReferencePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::GetReferencePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetReferencePositionResponse> should match
// service_traits::DataType< ::ros_mscl::GetReferencePosition >
template<>
struct DataType< ::ros_mscl::GetReferencePositionResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::GetReferencePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETREFERENCEPOSITION_H
