// Generated by gencpp from file ros_mscl/GetRelativePositionReference.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETRELATIVEPOSITIONREFERENCE_H
#define ROS_MSCL_MESSAGE_GETRELATIVEPOSITIONREFERENCE_H

#include <ros/service_traits.h>


#include <ros_mscl/GetRelativePositionReferenceRequest.h>
#include <ros_mscl/GetRelativePositionReferenceResponse.h>


namespace ros_mscl
{

struct GetRelativePositionReference
{

typedef GetRelativePositionReferenceRequest Request;
typedef GetRelativePositionReferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRelativePositionReference
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetRelativePositionReference > {
  static const char* value()
  {
    return "7778d2daa4ab0de5ddac855cca257e01";
  }

  static const char* value(const ::ros_mscl::GetRelativePositionReference&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetRelativePositionReference > {
  static const char* value()
  {
    return "ros_mscl/GetRelativePositionReference";
  }

  static const char* value(const ::ros_mscl::GetRelativePositionReference&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetRelativePositionReferenceRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetRelativePositionReference >
template<>
struct MD5Sum< ::ros_mscl::GetRelativePositionReferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::GetRelativePositionReferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetRelativePositionReferenceRequest> should match
// service_traits::DataType< ::ros_mscl::GetRelativePositionReference >
template<>
struct DataType< ::ros_mscl::GetRelativePositionReferenceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::GetRelativePositionReferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetRelativePositionReferenceResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetRelativePositionReference >
template<>
struct MD5Sum< ::ros_mscl::GetRelativePositionReferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::GetRelativePositionReferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetRelativePositionReferenceResponse> should match
// service_traits::DataType< ::ros_mscl::GetRelativePositionReference >
template<>
struct DataType< ::ros_mscl::GetRelativePositionReferenceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::GetRelativePositionReferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETRELATIVEPOSITIONREFERENCE_H
