// Generated by gencpp from file ros_mscl/GetSensor2VehicleOffset.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETSENSOR2VEHICLEOFFSET_H
#define ROS_MSCL_MESSAGE_GETSENSOR2VEHICLEOFFSET_H

#include <ros/service_traits.h>


#include <ros_mscl/GetSensor2VehicleOffsetRequest.h>
#include <ros_mscl/GetSensor2VehicleOffsetResponse.h>


namespace ros_mscl
{

struct GetSensor2VehicleOffset
{

typedef GetSensor2VehicleOffsetRequest Request;
typedef GetSensor2VehicleOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensor2VehicleOffset
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleOffset > {
  static const char* value()
  {
    return "336379c9adc329d4ecaa355471c3cacd";
  }

  static const char* value(const ::ros_mscl::GetSensor2VehicleOffset&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetSensor2VehicleOffset > {
  static const char* value()
  {
    return "ros_mscl/GetSensor2VehicleOffset";
  }

  static const char* value(const ::ros_mscl::GetSensor2VehicleOffset&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleOffsetRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleOffset >
template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetSensor2VehicleOffsetRequest> should match
// service_traits::DataType< ::ros_mscl::GetSensor2VehicleOffset >
template<>
struct DataType< ::ros_mscl::GetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleOffsetResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleOffset >
template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetSensor2VehicleOffsetResponse> should match
// service_traits::DataType< ::ros_mscl::GetSensor2VehicleOffset >
template<>
struct DataType< ::ros_mscl::GetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETSENSOR2VEHICLEOFFSET_H
