// Generated by gencpp from file ros_mscl/GetSensor2VehicleTransformation.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETSENSOR2VEHICLETRANSFORMATION_H
#define ROS_MSCL_MESSAGE_GETSENSOR2VEHICLETRANSFORMATION_H

#include <ros/service_traits.h>


#include <ros_mscl/GetSensor2VehicleTransformationRequest.h>
#include <ros_mscl/GetSensor2VehicleTransformationResponse.h>


namespace ros_mscl
{

struct GetSensor2VehicleTransformation
{

typedef GetSensor2VehicleTransformationRequest Request;
typedef GetSensor2VehicleTransformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensor2VehicleTransformation
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleTransformation > {
  static const char* value()
  {
    return "004f75cd783f40825cb5e1db7049f127";
  }

  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformation&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetSensor2VehicleTransformation > {
  static const char* value()
  {
    return "ros_mscl/GetSensor2VehicleTransformation";
  }

  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformation&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleTransformationRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleTransformation >
template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleTransformationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetSensor2VehicleTransformation >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetSensor2VehicleTransformationRequest> should match
// service_traits::DataType< ::ros_mscl::GetSensor2VehicleTransformation >
template<>
struct DataType< ::ros_mscl::GetSensor2VehicleTransformationRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetSensor2VehicleTransformation >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleTransformationResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetSensor2VehicleTransformation >
template<>
struct MD5Sum< ::ros_mscl::GetSensor2VehicleTransformationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetSensor2VehicleTransformation >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetSensor2VehicleTransformationResponse> should match
// service_traits::DataType< ::ros_mscl::GetSensor2VehicleTransformation >
template<>
struct DataType< ::ros_mscl::GetSensor2VehicleTransformationResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetSensor2VehicleTransformation >::value();
  }
  static const char* value(const ::ros_mscl::GetSensor2VehicleTransformationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETSENSOR2VEHICLETRANSFORMATION_H
