// Generated by gencpp from file ros_mscl/GetTareOrientationResponse.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETTAREORIENTATIONRESPONSE_H
#define ROS_MSCL_MESSAGE_GETTAREORIENTATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct GetTareOrientationResponse_
{
  typedef GetTareOrientationResponse_<ContainerAllocator> Type;

  GetTareOrientationResponse_()
    : axis(0)
    , success(false)  {
    }
  GetTareOrientationResponse_(const ContainerAllocator& _alloc)
    : axis(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int8_t _axis_type;
  _axis_type axis;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTareOrientationResponse_

typedef ::ros_mscl::GetTareOrientationResponse_<std::allocator<void> > GetTareOrientationResponse;

typedef boost::shared_ptr< ::ros_mscl::GetTareOrientationResponse > GetTareOrientationResponsePtr;
typedef boost::shared_ptr< ::ros_mscl::GetTareOrientationResponse const> GetTareOrientationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.axis == rhs.axis &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ecd93a5c8679ed9b5ed373f0919456";
  }

  static const char* value(const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ecd93a5c8679edULL;
  static const uint64_t static_value2 = 0x9b5ed373f0919456ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/GetTareOrientationResponse";
  }

  static const char* value(const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 axis\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTareOrientationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::GetTareOrientationResponse_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<int8_t>::stream(s, indent + "  ", v.axis);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETTAREORIENTATIONRESPONSE_H
