// Generated by gencpp from file ros_mscl/GetTareOrientation.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETTAREORIENTATION_H
#define ROS_MSCL_MESSAGE_GETTAREORIENTATION_H

#include <ros/service_traits.h>


#include <ros_mscl/GetTareOrientationRequest.h>
#include <ros_mscl/GetTareOrientationResponse.h>


namespace ros_mscl
{

struct GetTareOrientation
{

typedef GetTareOrientationRequest Request;
typedef GetTareOrientationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTareOrientation
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetTareOrientation > {
  static const char* value()
  {
    return "87ecd93a5c8679ed9b5ed373f0919456";
  }

  static const char* value(const ::ros_mscl::GetTareOrientation&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetTareOrientation > {
  static const char* value()
  {
    return "ros_mscl/GetTareOrientation";
  }

  static const char* value(const ::ros_mscl::GetTareOrientation&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetTareOrientationRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetTareOrientation >
template<>
struct MD5Sum< ::ros_mscl::GetTareOrientationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::GetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetTareOrientationRequest> should match
// service_traits::DataType< ::ros_mscl::GetTareOrientation >
template<>
struct DataType< ::ros_mscl::GetTareOrientationRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::GetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetTareOrientationResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetTareOrientation >
template<>
struct MD5Sum< ::ros_mscl::GetTareOrientationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::GetTareOrientationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetTareOrientationResponse> should match
// service_traits::DataType< ::ros_mscl::GetTareOrientation >
template<>
struct DataType< ::ros_mscl::GetTareOrientationResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::GetTareOrientationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETTAREORIENTATION_H
