// Generated by gencpp from file ros_mscl/GetZeroAngleUpdateThresholdResponse.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLDRESPONSE_H
#define ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct GetZeroAngleUpdateThresholdResponse_
{
  typedef GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> Type;

  GetZeroAngleUpdateThresholdResponse_()
    : enable(0)
    , threshold(0.0)
    , success(false)  {
    }
  GetZeroAngleUpdateThresholdResponse_(const ContainerAllocator& _alloc)
    : enable(0)
    , threshold(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int8_t _enable_type;
  _enable_type enable;

   typedef float _threshold_type;
  _threshold_type threshold;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetZeroAngleUpdateThresholdResponse_

typedef ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<std::allocator<void> > GetZeroAngleUpdateThresholdResponse;

typedef boost::shared_ptr< ::ros_mscl::GetZeroAngleUpdateThresholdResponse > GetZeroAngleUpdateThresholdResponsePtr;
typedef boost::shared_ptr< ::ros_mscl::GetZeroAngleUpdateThresholdResponse const> GetZeroAngleUpdateThresholdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.threshold == rhs.threshold &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator1> & lhs, const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d55bd0c555abfd31bce740efa684526";
  }

  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d55bd0c555abfd3ULL;
  static const uint64_t static_value2 = 0x1bce740efa684526ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/GetZeroAngleUpdateThresholdResponse";
  }

  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enable\n"
"float32 threshold\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.threshold);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetZeroAngleUpdateThresholdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::GetZeroAngleUpdateThresholdResponse_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLDRESPONSE_H
