// Generated by gencpp from file ros_mscl/GetZeroAngleUpdateThreshold.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLD_H
#define ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLD_H

#include <ros/service_traits.h>


#include <ros_mscl/GetZeroAngleUpdateThresholdRequest.h>
#include <ros_mscl/GetZeroAngleUpdateThresholdResponse.h>


namespace ros_mscl
{

struct GetZeroAngleUpdateThreshold
{

typedef GetZeroAngleUpdateThresholdRequest Request;
typedef GetZeroAngleUpdateThresholdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetZeroAngleUpdateThreshold
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::GetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "1d55bd0c555abfd31bce740efa684526";
  }

  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThreshold&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::GetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "ros_mscl/GetZeroAngleUpdateThreshold";
  }

  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThreshold&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::GetZeroAngleUpdateThresholdRequest> should match
// service_traits::MD5Sum< ::ros_mscl::GetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::GetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetZeroAngleUpdateThresholdRequest> should match
// service_traits::DataType< ::ros_mscl::GetZeroAngleUpdateThreshold >
template<>
struct DataType< ::ros_mscl::GetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::GetZeroAngleUpdateThresholdResponse> should match
// service_traits::MD5Sum< ::ros_mscl::GetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::GetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::GetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::GetZeroAngleUpdateThresholdResponse> should match
// service_traits::DataType< ::ros_mscl::GetZeroAngleUpdateThreshold >
template<>
struct DataType< ::ros_mscl::GetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::GetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::GetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_GETZEROANGLEUPDATETHRESHOLD_H
