// Generated by gencpp from file ros_mscl/InitFilterHeading.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_INITFILTERHEADING_H
#define ROS_MSCL_MESSAGE_INITFILTERHEADING_H

#include <ros/service_traits.h>


#include <ros_mscl/InitFilterHeadingRequest.h>
#include <ros_mscl/InitFilterHeadingResponse.h>


namespace ros_mscl
{

struct InitFilterHeading
{

typedef InitFilterHeadingRequest Request;
typedef InitFilterHeadingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitFilterHeading
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::InitFilterHeading > {
  static const char* value()
  {
    return "194939c001a63802dc4131cae92cda22";
  }

  static const char* value(const ::ros_mscl::InitFilterHeading&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::InitFilterHeading > {
  static const char* value()
  {
    return "ros_mscl/InitFilterHeading";
  }

  static const char* value(const ::ros_mscl::InitFilterHeading&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::InitFilterHeadingRequest> should match
// service_traits::MD5Sum< ::ros_mscl::InitFilterHeading >
template<>
struct MD5Sum< ::ros_mscl::InitFilterHeadingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::InitFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::InitFilterHeadingRequest> should match
// service_traits::DataType< ::ros_mscl::InitFilterHeading >
template<>
struct DataType< ::ros_mscl::InitFilterHeadingRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::InitFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::InitFilterHeadingResponse> should match
// service_traits::MD5Sum< ::ros_mscl::InitFilterHeading >
template<>
struct MD5Sum< ::ros_mscl::InitFilterHeadingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::InitFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterHeadingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::InitFilterHeadingResponse> should match
// service_traits::DataType< ::ros_mscl::InitFilterHeading >
template<>
struct DataType< ::ros_mscl::InitFilterHeadingResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::InitFilterHeading >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterHeadingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_INITFILTERHEADING_H
