// Generated by gencpp from file ros_mscl/InitFilterEuler.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_INITFILTEREULER_H
#define ROS_MSCL_MESSAGE_INITFILTEREULER_H

#include <ros/service_traits.h>


#include <ros_mscl/InitFilterEulerRequest.h>
#include <ros_mscl/InitFilterEulerResponse.h>


namespace ros_mscl
{

struct InitFilterEuler
{

typedef InitFilterEulerRequest Request;
typedef InitFilterEulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitFilterEuler
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::InitFilterEuler > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::ros_mscl::InitFilterEuler&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::InitFilterEuler > {
  static const char* value()
  {
    return "ros_mscl/InitFilterEuler";
  }

  static const char* value(const ::ros_mscl::InitFilterEuler&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::InitFilterEulerRequest> should match
// service_traits::MD5Sum< ::ros_mscl::InitFilterEuler >
template<>
struct MD5Sum< ::ros_mscl::InitFilterEulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::InitFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::InitFilterEulerRequest> should match
// service_traits::DataType< ::ros_mscl::InitFilterEuler >
template<>
struct DataType< ::ros_mscl::InitFilterEulerRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::InitFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::InitFilterEulerResponse> should match
// service_traits::MD5Sum< ::ros_mscl::InitFilterEuler >
template<>
struct MD5Sum< ::ros_mscl::InitFilterEulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::InitFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterEulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::InitFilterEulerResponse> should match
// service_traits::DataType< ::ros_mscl::InitFilterEuler >
template<>
struct DataType< ::ros_mscl::InitFilterEulerResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::InitFilterEuler >::value();
  }
  static const char* value(const ::ros_mscl::InitFilterEulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_INITFILTEREULER_H
