// Generated by gencpp from file ros_mscl/SetAccelNoise.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETACCELNOISE_H
#define ROS_MSCL_MESSAGE_SETACCELNOISE_H

#include <ros/service_traits.h>


#include <ros_mscl/SetAccelNoiseRequest.h>
#include <ros_mscl/SetAccelNoiseResponse.h>


namespace ros_mscl
{

struct SetAccelNoise
{

typedef SetAccelNoiseRequest Request;
typedef SetAccelNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelNoise
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetAccelNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::ros_mscl::SetAccelNoise&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetAccelNoise > {
  static const char* value()
  {
    return "ros_mscl/SetAccelNoise";
  }

  static const char* value(const ::ros_mscl::SetAccelNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetAccelNoiseRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelNoise >
template<>
struct MD5Sum< ::ros_mscl::SetAccelNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelNoiseRequest> should match
// service_traits::DataType< ::ros_mscl::SetAccelNoise >
template<>
struct DataType< ::ros_mscl::SetAccelNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetAccelNoiseResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelNoise >
template<>
struct MD5Sum< ::ros_mscl::SetAccelNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelNoiseResponse> should match
// service_traits::DataType< ::ros_mscl::SetAccelNoise >
template<>
struct DataType< ::ros_mscl::SetAccelNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETACCELNOISE_H
