// Generated by gencpp from file ros_mscl/SetAccelBias.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETACCELBIAS_H
#define ROS_MSCL_MESSAGE_SETACCELBIAS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetAccelBiasRequest.h>
#include <ros_mscl/SetAccelBiasResponse.h>


namespace ros_mscl
{

struct SetAccelBias
{

typedef SetAccelBiasRequest Request;
typedef SetAccelBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelBias
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetAccelBias > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::ros_mscl::SetAccelBias&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetAccelBias > {
  static const char* value()
  {
    return "ros_mscl/SetAccelBias";
  }

  static const char* value(const ::ros_mscl::SetAccelBias&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelBias >
template<>
struct MD5Sum< ::ros_mscl::SetAccelBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelBias >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelBiasRequest> should match
// service_traits::DataType< ::ros_mscl::SetAccelBias >
template<>
struct DataType< ::ros_mscl::SetAccelBiasRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelBias >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelBias >
template<>
struct MD5Sum< ::ros_mscl::SetAccelBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelBias >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelBiasResponse> should match
// service_traits::DataType< ::ros_mscl::SetAccelBias >
template<>
struct DataType< ::ros_mscl::SetAccelBiasResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelBias >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETACCELBIAS_H
