// Generated by gencpp from file ros_mscl/SetAccelAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETACCELADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_SETACCELADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetAccelAdaptiveValsRequest.h>
#include <ros_mscl/SetAccelAdaptiveValsResponse.h>


namespace ros_mscl
{

struct SetAccelAdaptiveVals
{

typedef SetAccelAdaptiveValsRequest Request;
typedef SetAccelAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetAccelAdaptiveVals > {
  static const char* value()
  {
    return "f4333508f865a0d6b01f8e48e0168654";
  }

  static const char* value(const ::ros_mscl::SetAccelAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetAccelAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/SetAccelAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::SetAccelAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetAccelAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetAccelAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::SetAccelAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetAccelAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetAccelAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetAccelAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::SetAccelAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetAccelAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETACCELADAPTIVEVALS_H
