// Generated by gencpp from file ros_mscl/SetAccelBiasModel.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETACCELBIASMODEL_H
#define ROS_MSCL_MESSAGE_SETACCELBIASMODEL_H

#include <ros/service_traits.h>


#include <ros_mscl/SetAccelBiasModelRequest.h>
#include <ros_mscl/SetAccelBiasModelResponse.h>


namespace ros_mscl
{

struct SetAccelBiasModel
{

typedef SetAccelBiasModelRequest Request;
typedef SetAccelBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelBiasModel
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetAccelBiasModel > {
  static const char* value()
  {
    return "f3cdd18c97add875be98974ab1d992b9";
  }

  static const char* value(const ::ros_mscl::SetAccelBiasModel&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetAccelBiasModel > {
  static const char* value()
  {
    return "ros_mscl/SetAccelBiasModel";
  }

  static const char* value(const ::ros_mscl::SetAccelBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasModelRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasModel >
template<>
struct MD5Sum< ::ros_mscl::SetAccelBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelBiasModelRequest> should match
// service_traits::DataType< ::ros_mscl::SetAccelBiasModel >
template<>
struct DataType< ::ros_mscl::SetAccelBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasModelResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetAccelBiasModel >
template<>
struct MD5Sum< ::ros_mscl::SetAccelBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetAccelBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetAccelBiasModelResponse> should match
// service_traits::DataType< ::ros_mscl::SetAccelBiasModel >
template<>
struct DataType< ::ros_mscl::SetAccelBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetAccelBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetAccelBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETACCELBIASMODEL_H
