// Generated by gencpp from file ros_mscl/SetConingScullingComp.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETCONINGSCULLINGCOMP_H
#define ROS_MSCL_MESSAGE_SETCONINGSCULLINGCOMP_H

#include <ros/service_traits.h>


#include <ros_mscl/SetConingScullingCompRequest.h>
#include <ros_mscl/SetConingScullingCompResponse.h>


namespace ros_mscl
{

struct SetConingScullingComp
{

typedef SetConingScullingCompRequest Request;
typedef SetConingScullingCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetConingScullingComp
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetConingScullingComp > {
  static const char* value()
  {
    return "f7caf6e1618fb8cc640ac244d6c53d7f";
  }

  static const char* value(const ::ros_mscl::SetConingScullingComp&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetConingScullingComp > {
  static const char* value()
  {
    return "ros_mscl/SetConingScullingComp";
  }

  static const char* value(const ::ros_mscl::SetConingScullingComp&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetConingScullingCompRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetConingScullingComp >
template<>
struct MD5Sum< ::ros_mscl::SetConingScullingCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::SetConingScullingCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetConingScullingCompRequest> should match
// service_traits::DataType< ::ros_mscl::SetConingScullingComp >
template<>
struct DataType< ::ros_mscl::SetConingScullingCompRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::SetConingScullingCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetConingScullingCompResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetConingScullingComp >
template<>
struct MD5Sum< ::ros_mscl::SetConingScullingCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::SetConingScullingCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetConingScullingCompResponse> should match
// service_traits::DataType< ::ros_mscl::SetConingScullingComp >
template<>
struct DataType< ::ros_mscl::SetConingScullingCompResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetConingScullingComp >::value();
  }
  static const char* value(const ::ros_mscl::SetConingScullingCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETCONINGSCULLINGCOMP_H
