// Generated by gencpp from file ros_mscl/SetEstimationControlFlags.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETESTIMATIONCONTROLFLAGS_H
#define ROS_MSCL_MESSAGE_SETESTIMATIONCONTROLFLAGS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetEstimationControlFlagsRequest.h>
#include <ros_mscl/SetEstimationControlFlagsResponse.h>


namespace ros_mscl
{

struct SetEstimationControlFlags
{

typedef SetEstimationControlFlagsRequest Request;
typedef SetEstimationControlFlagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEstimationControlFlags
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetEstimationControlFlags > {
  static const char* value()
  {
    return "7efd025d74deaecd09a7eaf56530e702";
  }

  static const char* value(const ::ros_mscl::SetEstimationControlFlags&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetEstimationControlFlags > {
  static const char* value()
  {
    return "ros_mscl/SetEstimationControlFlags";
  }

  static const char* value(const ::ros_mscl::SetEstimationControlFlags&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetEstimationControlFlagsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetEstimationControlFlags >
template<>
struct MD5Sum< ::ros_mscl::SetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::SetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetEstimationControlFlagsRequest> should match
// service_traits::DataType< ::ros_mscl::SetEstimationControlFlags >
template<>
struct DataType< ::ros_mscl::SetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::SetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetEstimationControlFlagsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetEstimationControlFlags >
template<>
struct MD5Sum< ::ros_mscl::SetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::SetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetEstimationControlFlagsResponse> should match
// service_traits::DataType< ::ros_mscl::SetEstimationControlFlags >
template<>
struct DataType< ::ros_mscl::SetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::ros_mscl::SetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETESTIMATIONCONTROLFLAGS_H
