// Generated by gencpp from file ros_mscl/SetGravityAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETGRAVITYADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_SETGRAVITYADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetGravityAdaptiveValsRequest.h>
#include <ros_mscl/SetGravityAdaptiveValsResponse.h>


namespace ros_mscl
{

struct SetGravityAdaptiveVals
{

typedef SetGravityAdaptiveValsRequest Request;
typedef SetGravityAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGravityAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetGravityAdaptiveVals > {
  static const char* value()
  {
    return "f4333508f865a0d6b01f8e48e0168654";
  }

  static const char* value(const ::ros_mscl::SetGravityAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetGravityAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/SetGravityAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::SetGravityAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetGravityAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetGravityAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetGravityAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGravityAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetGravityAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGravityAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::SetGravityAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetGravityAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGravityAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetGravityAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetGravityAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetGravityAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetGravityAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGravityAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetGravityAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGravityAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::SetGravityAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetGravityAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGravityAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetGravityAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETGRAVITYADAPTIVEVALS_H
