// Generated by gencpp from file ros_mscl/SetGyroBias.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETGYROBIAS_H
#define ROS_MSCL_MESSAGE_SETGYROBIAS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetGyroBiasRequest.h>
#include <ros_mscl/SetGyroBiasResponse.h>


namespace ros_mscl
{

struct SetGyroBias
{

typedef SetGyroBiasRequest Request;
typedef SetGyroBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroBias
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetGyroBias > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::ros_mscl::SetGyroBias&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetGyroBias > {
  static const char* value()
  {
    return "ros_mscl/SetGyroBias";
  }

  static const char* value(const ::ros_mscl::SetGyroBias&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroBias >
template<>
struct MD5Sum< ::ros_mscl::SetGyroBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroBiasRequest> should match
// service_traits::DataType< ::ros_mscl::SetGyroBias >
template<>
struct DataType< ::ros_mscl::SetGyroBiasRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroBias >
template<>
struct MD5Sum< ::ros_mscl::SetGyroBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroBiasResponse> should match
// service_traits::DataType< ::ros_mscl::SetGyroBias >
template<>
struct DataType< ::ros_mscl::SetGyroBiasResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroBias >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETGYROBIAS_H
