// Generated by gencpp from file ros_mscl/SetGyroBiasModel.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETGYROBIASMODEL_H
#define ROS_MSCL_MESSAGE_SETGYROBIASMODEL_H

#include <ros/service_traits.h>


#include <ros_mscl/SetGyroBiasModelRequest.h>
#include <ros_mscl/SetGyroBiasModelResponse.h>


namespace ros_mscl
{

struct SetGyroBiasModel
{

typedef SetGyroBiasModelRequest Request;
typedef SetGyroBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroBiasModel
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetGyroBiasModel > {
  static const char* value()
  {
    return "f3cdd18c97add875be98974ab1d992b9";
  }

  static const char* value(const ::ros_mscl::SetGyroBiasModel&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetGyroBiasModel > {
  static const char* value()
  {
    return "ros_mscl/SetGyroBiasModel";
  }

  static const char* value(const ::ros_mscl::SetGyroBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasModelRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasModel >
template<>
struct MD5Sum< ::ros_mscl::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroBiasModelRequest> should match
// service_traits::DataType< ::ros_mscl::SetGyroBiasModel >
template<>
struct DataType< ::ros_mscl::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasModelResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroBiasModel >
template<>
struct MD5Sum< ::ros_mscl::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroBiasModelResponse> should match
// service_traits::DataType< ::ros_mscl::SetGyroBiasModel >
template<>
struct DataType< ::ros_mscl::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroBiasModel >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETGYROBIASMODEL_H
