// Generated by gencpp from file ros_mscl/SetGyroNoise.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETGYRONOISE_H
#define ROS_MSCL_MESSAGE_SETGYRONOISE_H

#include <ros/service_traits.h>


#include <ros_mscl/SetGyroNoiseRequest.h>
#include <ros_mscl/SetGyroNoiseResponse.h>


namespace ros_mscl
{

struct SetGyroNoise
{

typedef SetGyroNoiseRequest Request;
typedef SetGyroNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroNoise
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetGyroNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::ros_mscl::SetGyroNoise&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetGyroNoise > {
  static const char* value()
  {
    return "ros_mscl/SetGyroNoise";
  }

  static const char* value(const ::ros_mscl::SetGyroNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetGyroNoiseRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroNoise >
template<>
struct MD5Sum< ::ros_mscl::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroNoiseRequest> should match
// service_traits::DataType< ::ros_mscl::SetGyroNoise >
template<>
struct DataType< ::ros_mscl::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetGyroNoiseResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetGyroNoise >
template<>
struct MD5Sum< ::ros_mscl::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetGyroNoiseResponse> should match
// service_traits::DataType< ::ros_mscl::SetGyroNoise >
template<>
struct DataType< ::ros_mscl::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetGyroNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetGyroNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETGYRONOISE_H
