// Generated by gencpp from file ros_mscl/SetHeadingSource.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETHEADINGSOURCE_H
#define ROS_MSCL_MESSAGE_SETHEADINGSOURCE_H

#include <ros/service_traits.h>


#include <ros_mscl/SetHeadingSourceRequest.h>
#include <ros_mscl/SetHeadingSourceResponse.h>


namespace ros_mscl
{

struct SetHeadingSource
{

typedef SetHeadingSourceRequest Request;
typedef SetHeadingSourceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHeadingSource
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetHeadingSource > {
  static const char* value()
  {
    return "cafce2dffb0d75024a8bceb4a3f50704";
  }

  static const char* value(const ::ros_mscl::SetHeadingSource&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetHeadingSource > {
  static const char* value()
  {
    return "ros_mscl/SetHeadingSource";
  }

  static const char* value(const ::ros_mscl::SetHeadingSource&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetHeadingSourceRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetHeadingSource >
template<>
struct MD5Sum< ::ros_mscl::SetHeadingSourceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::SetHeadingSourceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetHeadingSourceRequest> should match
// service_traits::DataType< ::ros_mscl::SetHeadingSource >
template<>
struct DataType< ::ros_mscl::SetHeadingSourceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::SetHeadingSourceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetHeadingSourceResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetHeadingSource >
template<>
struct MD5Sum< ::ros_mscl::SetHeadingSourceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::SetHeadingSourceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetHeadingSourceResponse> should match
// service_traits::DataType< ::ros_mscl::SetHeadingSource >
template<>
struct DataType< ::ros_mscl::SetHeadingSourceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetHeadingSource >::value();
  }
  static const char* value(const ::ros_mscl::SetHeadingSourceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETHEADINGSOURCE_H
