// Generated by gencpp from file ros_mscl/SetHardIronValues.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETHARDIRONVALUES_H
#define ROS_MSCL_MESSAGE_SETHARDIRONVALUES_H

#include <ros/service_traits.h>


#include <ros_mscl/SetHardIronValuesRequest.h>
#include <ros_mscl/SetHardIronValuesResponse.h>


namespace ros_mscl
{

struct SetHardIronValues
{

typedef SetHardIronValuesRequest Request;
typedef SetHardIronValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHardIronValues
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetHardIronValues > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::ros_mscl::SetHardIronValues&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetHardIronValues > {
  static const char* value()
  {
    return "ros_mscl/SetHardIronValues";
  }

  static const char* value(const ::ros_mscl::SetHardIronValues&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetHardIronValuesRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetHardIronValues >
template<>
struct MD5Sum< ::ros_mscl::SetHardIronValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::SetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetHardIronValuesRequest> should match
// service_traits::DataType< ::ros_mscl::SetHardIronValues >
template<>
struct DataType< ::ros_mscl::SetHardIronValuesRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::SetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetHardIronValuesResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetHardIronValues >
template<>
struct MD5Sum< ::ros_mscl::SetHardIronValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::SetHardIronValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetHardIronValuesResponse> should match
// service_traits::DataType< ::ros_mscl::SetHardIronValues >
template<>
struct DataType< ::ros_mscl::SetHardIronValuesResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetHardIronValues >::value();
  }
  static const char* value(const ::ros_mscl::SetHardIronValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETHARDIRONVALUES_H
