// Generated by gencpp from file ros_mscl/SetHeadingSourceRequest.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETHEADINGSOURCEREQUEST_H
#define ROS_MSCL_MESSAGE_SETHEADINGSOURCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct SetHeadingSourceRequest_
{
  typedef SetHeadingSourceRequest_<ContainerAllocator> Type;

  SetHeadingSourceRequest_()
    : headingSource(0)  {
    }
  SetHeadingSourceRequest_(const ContainerAllocator& _alloc)
    : headingSource(0)  {
  (void)_alloc;
    }



   typedef int8_t _headingSource_type;
  _headingSource_type headingSource;





  typedef boost::shared_ptr< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHeadingSourceRequest_

typedef ::ros_mscl::SetHeadingSourceRequest_<std::allocator<void> > SetHeadingSourceRequest;

typedef boost::shared_ptr< ::ros_mscl::SetHeadingSourceRequest > SetHeadingSourceRequestPtr;
typedef boost::shared_ptr< ::ros_mscl::SetHeadingSourceRequest const> SetHeadingSourceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.headingSource == rhs.headingSource;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd83d4bad7b478d6a2d23a0e890cba23";
  }

  static const char* value(const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd83d4bad7b478d6ULL;
  static const uint64_t static_value2 = 0xa2d23a0e890cba23ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/SetHeadingSourceRequest";
  }

  static const char* value(const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 headingSource\n"
;
  }

  static const char* value(const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.headingSource);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHeadingSourceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::SetHeadingSourceRequest_<ContainerAllocator>& v)
  {
    s << indent << "headingSource: ";
    Printer<int8_t>::stream(s, indent + "  ", v.headingSource);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETHEADINGSOURCEREQUEST_H
