// Generated by gencpp from file ros_mscl/SetHardIronValuesRequest.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETHARDIRONVALUESREQUEST_H
#define ROS_MSCL_MESSAGE_SETHARDIRONVALUESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace ros_mscl
{
template <class ContainerAllocator>
struct SetHardIronValuesRequest_
{
  typedef SetHardIronValuesRequest_<ContainerAllocator> Type;

  SetHardIronValuesRequest_()
    : bias()  {
    }
  SetHardIronValuesRequest_(const ContainerAllocator& _alloc)
    : bias(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _bias_type;
  _bias_type bias;





  typedef boost::shared_ptr< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHardIronValuesRequest_

typedef ::ros_mscl::SetHardIronValuesRequest_<std::allocator<void> > SetHardIronValuesRequest;

typedef boost::shared_ptr< ::ros_mscl::SetHardIronValuesRequest > SetHardIronValuesRequestPtr;
typedef boost::shared_ptr< ::ros_mscl::SetHardIronValuesRequest const> SetHardIronValuesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.bias == rhs.bias;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af1f260075d9ba9bd73ca10c6a45df07";
  }

  static const char* value(const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf1f260075d9ba9bULL;
  static const uint64_t static_value2 = 0xd73ca10c6a45df07ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/SetHardIronValuesRequest";
  }

  static const char* value(const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 bias\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bias);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHardIronValuesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::SetHardIronValuesRequest_<ContainerAllocator>& v)
  {
    s << indent << "bias: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.bias);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETHARDIRONVALUESREQUEST_H
