// Generated by gencpp from file ros_mscl/SetMagAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETMAGADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_SETMAGADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetMagAdaptiveValsRequest.h>
#include <ros_mscl/SetMagAdaptiveValsResponse.h>


namespace ros_mscl
{

struct SetMagAdaptiveVals
{

typedef SetMagAdaptiveValsRequest Request;
typedef SetMagAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMagAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetMagAdaptiveVals > {
  static const char* value()
  {
    return "f4333508f865a0d6b01f8e48e0168654";
  }

  static const char* value(const ::ros_mscl::SetMagAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetMagAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/SetMagAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::SetMagAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetMagAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetMagAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::SetMagAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetMagAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetMagAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetMagAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::SetMagAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetMagAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETMAGADAPTIVEVALS_H
