// Generated by gencpp from file ros_mscl/SetMagDipAdaptiveVals.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETMAGDIPADAPTIVEVALS_H
#define ROS_MSCL_MESSAGE_SETMAGDIPADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <ros_mscl/SetMagDipAdaptiveValsRequest.h>
#include <ros_mscl/SetMagDipAdaptiveValsResponse.h>


namespace ros_mscl
{

struct SetMagDipAdaptiveVals
{

typedef SetMagDipAdaptiveValsRequest Request;
typedef SetMagDipAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMagDipAdaptiveVals
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "c71450f947e543c107e6e7b633ac2f16";
  }

  static const char* value(const ::ros_mscl::SetMagDipAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "ros_mscl/SetMagDipAdaptiveVals";
  }

  static const char* value(const ::ros_mscl::SetMagDipAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetMagDipAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagDipAdaptiveValsRequest> should match
// service_traits::DataType< ::ros_mscl::SetMagDipAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetMagDipAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::ros_mscl::SetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagDipAdaptiveValsResponse> should match
// service_traits::DataType< ::ros_mscl::SetMagDipAdaptiveVals >
template<>
struct DataType< ::ros_mscl::SetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::ros_mscl::SetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETMAGDIPADAPTIVEVALS_H
