// Generated by gencpp from file ros_mscl/SetMagNoise.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETMAGNOISE_H
#define ROS_MSCL_MESSAGE_SETMAGNOISE_H

#include <ros/service_traits.h>


#include <ros_mscl/SetMagNoiseRequest.h>
#include <ros_mscl/SetMagNoiseResponse.h>


namespace ros_mscl
{

struct SetMagNoise
{

typedef SetMagNoiseRequest Request;
typedef SetMagNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMagNoise
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetMagNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::ros_mscl::SetMagNoise&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetMagNoise > {
  static const char* value()
  {
    return "ros_mscl/SetMagNoise";
  }

  static const char* value(const ::ros_mscl::SetMagNoise&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetMagNoiseRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagNoise >
template<>
struct MD5Sum< ::ros_mscl::SetMagNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagNoiseRequest> should match
// service_traits::DataType< ::ros_mscl::SetMagNoise >
template<>
struct DataType< ::ros_mscl::SetMagNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetMagNoiseResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetMagNoise >
template<>
struct MD5Sum< ::ros_mscl::SetMagNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetMagNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetMagNoiseResponse> should match
// service_traits::DataType< ::ros_mscl::SetMagNoise >
template<>
struct DataType< ::ros_mscl::SetMagNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetMagNoise >::value();
  }
  static const char* value(const ::ros_mscl::SetMagNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETMAGNOISE_H
