// Generated by gencpp from file ros_mscl/SetRelativePositionReference.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETRELATIVEPOSITIONREFERENCE_H
#define ROS_MSCL_MESSAGE_SETRELATIVEPOSITIONREFERENCE_H

#include <ros/service_traits.h>


#include <ros_mscl/SetRelativePositionReferenceRequest.h>
#include <ros_mscl/SetRelativePositionReferenceResponse.h>


namespace ros_mscl
{

struct SetRelativePositionReference
{

typedef SetRelativePositionReferenceRequest Request;
typedef SetRelativePositionReferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRelativePositionReference
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetRelativePositionReference > {
  static const char* value()
  {
    return "322dca82c4e06e7f4805393b2e113aed";
  }

  static const char* value(const ::ros_mscl::SetRelativePositionReference&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetRelativePositionReference > {
  static const char* value()
  {
    return "ros_mscl/SetRelativePositionReference";
  }

  static const char* value(const ::ros_mscl::SetRelativePositionReference&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetRelativePositionReferenceRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetRelativePositionReference >
template<>
struct MD5Sum< ::ros_mscl::SetRelativePositionReferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::SetRelativePositionReferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetRelativePositionReferenceRequest> should match
// service_traits::DataType< ::ros_mscl::SetRelativePositionReference >
template<>
struct DataType< ::ros_mscl::SetRelativePositionReferenceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::SetRelativePositionReferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetRelativePositionReferenceResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetRelativePositionReference >
template<>
struct MD5Sum< ::ros_mscl::SetRelativePositionReferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::SetRelativePositionReferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetRelativePositionReferenceResponse> should match
// service_traits::DataType< ::ros_mscl::SetRelativePositionReference >
template<>
struct DataType< ::ros_mscl::SetRelativePositionReferenceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetRelativePositionReference >::value();
  }
  static const char* value(const ::ros_mscl::SetRelativePositionReferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETRELATIVEPOSITIONREFERENCE_H
