// Generated by gencpp from file ros_mscl/SetReferencePosition.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETREFERENCEPOSITION_H
#define ROS_MSCL_MESSAGE_SETREFERENCEPOSITION_H

#include <ros/service_traits.h>


#include <ros_mscl/SetReferencePositionRequest.h>
#include <ros_mscl/SetReferencePositionResponse.h>


namespace ros_mscl
{

struct SetReferencePosition
{

typedef SetReferencePositionRequest Request;
typedef SetReferencePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetReferencePosition
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetReferencePosition > {
  static const char* value()
  {
    return "eed8c009a979878261617f53e8264ddc";
  }

  static const char* value(const ::ros_mscl::SetReferencePosition&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetReferencePosition > {
  static const char* value()
  {
    return "ros_mscl/SetReferencePosition";
  }

  static const char* value(const ::ros_mscl::SetReferencePosition&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetReferencePositionRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetReferencePosition >
template<>
struct MD5Sum< ::ros_mscl::SetReferencePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::SetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetReferencePositionRequest> should match
// service_traits::DataType< ::ros_mscl::SetReferencePosition >
template<>
struct DataType< ::ros_mscl::SetReferencePositionRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::SetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetReferencePositionResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetReferencePosition >
template<>
struct MD5Sum< ::ros_mscl::SetReferencePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::SetReferencePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetReferencePositionResponse> should match
// service_traits::DataType< ::ros_mscl::SetReferencePosition >
template<>
struct DataType< ::ros_mscl::SetReferencePositionResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetReferencePosition >::value();
  }
  static const char* value(const ::ros_mscl::SetReferencePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETREFERENCEPOSITION_H
