// Generated by gencpp from file ros_mscl/SetSensor2VehicleOffset.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEOFFSET_H
#define ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEOFFSET_H

#include <ros/service_traits.h>


#include <ros_mscl/SetSensor2VehicleOffsetRequest.h>
#include <ros_mscl/SetSensor2VehicleOffsetResponse.h>


namespace ros_mscl
{

struct SetSensor2VehicleOffset
{

typedef SetSensor2VehicleOffsetRequest Request;
typedef SetSensor2VehicleOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensor2VehicleOffset
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleOffset > {
  static const char* value()
  {
    return "17d27ff1259ce523baf9de57b7c37e18";
  }

  static const char* value(const ::ros_mscl::SetSensor2VehicleOffset&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetSensor2VehicleOffset > {
  static const char* value()
  {
    return "ros_mscl/SetSensor2VehicleOffset";
  }

  static const char* value(const ::ros_mscl::SetSensor2VehicleOffset&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleOffsetRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleOffset >
template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensor2VehicleOffsetRequest> should match
// service_traits::DataType< ::ros_mscl::SetSensor2VehicleOffset >
template<>
struct DataType< ::ros_mscl::SetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleOffsetResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleOffset >
template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensor2VehicleOffsetResponse> should match
// service_traits::DataType< ::ros_mscl::SetSensor2VehicleOffset >
template<>
struct DataType< ::ros_mscl::SetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEOFFSET_H
