// Generated by gencpp from file ros_mscl/SetSoftIronMatrix.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETSOFTIRONMATRIX_H
#define ROS_MSCL_MESSAGE_SETSOFTIRONMATRIX_H

#include <ros/service_traits.h>


#include <ros_mscl/SetSoftIronMatrixRequest.h>
#include <ros_mscl/SetSoftIronMatrixResponse.h>


namespace ros_mscl
{

struct SetSoftIronMatrix
{

typedef SetSoftIronMatrixRequest Request;
typedef SetSoftIronMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSoftIronMatrix
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetSoftIronMatrix > {
  static const char* value()
  {
    return "ec07578ea93b9bb8b21d87ab5d1f0c81";
  }

  static const char* value(const ::ros_mscl::SetSoftIronMatrix&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetSoftIronMatrix > {
  static const char* value()
  {
    return "ros_mscl/SetSoftIronMatrix";
  }

  static const char* value(const ::ros_mscl::SetSoftIronMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetSoftIronMatrixRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetSoftIronMatrix >
template<>
struct MD5Sum< ::ros_mscl::SetSoftIronMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSoftIronMatrix >::value();
  }
  static const char* value(const ::ros_mscl::SetSoftIronMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSoftIronMatrixRequest> should match
// service_traits::DataType< ::ros_mscl::SetSoftIronMatrix >
template<>
struct DataType< ::ros_mscl::SetSoftIronMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSoftIronMatrix >::value();
  }
  static const char* value(const ::ros_mscl::SetSoftIronMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetSoftIronMatrixResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetSoftIronMatrix >
template<>
struct MD5Sum< ::ros_mscl::SetSoftIronMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSoftIronMatrix >::value();
  }
  static const char* value(const ::ros_mscl::SetSoftIronMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSoftIronMatrixResponse> should match
// service_traits::DataType< ::ros_mscl::SetSoftIronMatrix >
template<>
struct DataType< ::ros_mscl::SetSoftIronMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSoftIronMatrix >::value();
  }
  static const char* value(const ::ros_mscl::SetSoftIronMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETSOFTIRONMATRIX_H
