// Generated by gencpp from file ros_mscl/SetSensor2VehicleRotation.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEROTATION_H
#define ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEROTATION_H

#include <ros/service_traits.h>


#include <ros_mscl/SetSensor2VehicleRotationRequest.h>
#include <ros_mscl/SetSensor2VehicleRotationResponse.h>


namespace ros_mscl
{

struct SetSensor2VehicleRotation
{

typedef SetSensor2VehicleRotationRequest Request;
typedef SetSensor2VehicleRotationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensor2VehicleRotation
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleRotation > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::ros_mscl::SetSensor2VehicleRotation&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetSensor2VehicleRotation > {
  static const char* value()
  {
    return "ros_mscl/SetSensor2VehicleRotation";
  }

  static const char* value(const ::ros_mscl::SetSensor2VehicleRotation&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleRotationRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleRotation >
template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleRotationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleRotationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensor2VehicleRotationRequest> should match
// service_traits::DataType< ::ros_mscl::SetSensor2VehicleRotation >
template<>
struct DataType< ::ros_mscl::SetSensor2VehicleRotationRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleRotationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleRotationResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetSensor2VehicleRotation >
template<>
struct MD5Sum< ::ros_mscl::SetSensor2VehicleRotationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleRotationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetSensor2VehicleRotationResponse> should match
// service_traits::DataType< ::ros_mscl::SetSensor2VehicleRotation >
template<>
struct DataType< ::ros_mscl::SetSensor2VehicleRotationResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::ros_mscl::SetSensor2VehicleRotationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETSENSOR2VEHICLEROTATION_H
