// Generated by gencpp from file ros_mscl/SetTareOrientation.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETTAREORIENTATION_H
#define ROS_MSCL_MESSAGE_SETTAREORIENTATION_H

#include <ros/service_traits.h>


#include <ros_mscl/SetTareOrientationRequest.h>
#include <ros_mscl/SetTareOrientationResponse.h>


namespace ros_mscl
{

struct SetTareOrientation
{

typedef SetTareOrientationRequest Request;
typedef SetTareOrientationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTareOrientation
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetTareOrientation > {
  static const char* value()
  {
    return "75811cb68205ae4484ed796af90a6397";
  }

  static const char* value(const ::ros_mscl::SetTareOrientation&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetTareOrientation > {
  static const char* value()
  {
    return "ros_mscl/SetTareOrientation";
  }

  static const char* value(const ::ros_mscl::SetTareOrientation&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetTareOrientationRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetTareOrientation >
template<>
struct MD5Sum< ::ros_mscl::SetTareOrientationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::SetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetTareOrientationRequest> should match
// service_traits::DataType< ::ros_mscl::SetTareOrientation >
template<>
struct DataType< ::ros_mscl::SetTareOrientationRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::SetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetTareOrientationResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetTareOrientation >
template<>
struct MD5Sum< ::ros_mscl::SetTareOrientationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::SetTareOrientationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetTareOrientationResponse> should match
// service_traits::DataType< ::ros_mscl::SetTareOrientation >
template<>
struct DataType< ::ros_mscl::SetTareOrientationResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetTareOrientation >::value();
  }
  static const char* value(const ::ros_mscl::SetTareOrientationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETTAREORIENTATION_H
