// Generated by gencpp from file ros_mscl/SetZeroVelocityUpdateThresholdRequest.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLDREQUEST_H
#define ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mscl
{
template <class ContainerAllocator>
struct SetZeroVelocityUpdateThresholdRequest_
{
  typedef SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> Type;

  SetZeroVelocityUpdateThresholdRequest_()
    : enable(0)
    , threshold(0.0)  {
    }
  SetZeroVelocityUpdateThresholdRequest_(const ContainerAllocator& _alloc)
    : enable(0)
    , threshold(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _enable_type;
  _enable_type enable;

   typedef float _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetZeroVelocityUpdateThresholdRequest_

typedef ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<std::allocator<void> > SetZeroVelocityUpdateThresholdRequest;

typedef boost::shared_ptr< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest > SetZeroVelocityUpdateThresholdRequestPtr;
typedef boost::shared_ptr< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest const> SetZeroVelocityUpdateThresholdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator1> & lhs, const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_mscl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eacdc5ab3df5e6c977f6645124a7f61";
  }

  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eacdc5ab3df5e6cULL;
  static const uint64_t static_value2 = 0x977f6645124a7f61ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mscl/SetZeroVelocityUpdateThresholdRequest";
  }

  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enable\n"
"float32 threshold\n"
;
  }

  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetZeroVelocityUpdateThresholdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLDREQUEST_H
