// Generated by gencpp from file ros_mscl/SetZeroVelocityUpdateThreshold.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLD_H
#define ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLD_H

#include <ros/service_traits.h>


#include <ros_mscl/SetZeroVelocityUpdateThresholdRequest.h>
#include <ros_mscl/SetZeroVelocityUpdateThresholdResponse.h>


namespace ros_mscl
{

struct SetZeroVelocityUpdateThreshold
{

typedef SetZeroVelocityUpdateThresholdRequest Request;
typedef SetZeroVelocityUpdateThresholdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetZeroVelocityUpdateThreshold
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThreshold > {
  static const char* value()
  {
    return "ea1115ed39d8a581530c7c251ee443e6";
  }

  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThreshold&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetZeroVelocityUpdateThreshold > {
  static const char* value()
  {
    return "ros_mscl/SetZeroVelocityUpdateThreshold";
  }

  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThreshold&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest> should match
// service_traits::DataType< ::ros_mscl::SetZeroVelocityUpdateThreshold >
template<>
struct DataType< ::ros_mscl::SetZeroVelocityUpdateThresholdRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetZeroVelocityUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThresholdResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThresholdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetZeroVelocityUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetZeroVelocityUpdateThresholdResponse> should match
// service_traits::DataType< ::ros_mscl::SetZeroVelocityUpdateThreshold >
template<>
struct DataType< ::ros_mscl::SetZeroVelocityUpdateThresholdResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetZeroVelocityUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroVelocityUpdateThresholdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETZEROVELOCITYUPDATETHRESHOLD_H
