// Generated by gencpp from file ros_mscl/SetZeroAngleUpdateThreshold.msg
// DO NOT EDIT!


#ifndef ROS_MSCL_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H
#define ROS_MSCL_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H

#include <ros/service_traits.h>


#include <ros_mscl/SetZeroAngleUpdateThresholdRequest.h>
#include <ros_mscl/SetZeroAngleUpdateThresholdResponse.h>


namespace ros_mscl
{

struct SetZeroAngleUpdateThreshold
{

typedef SetZeroAngleUpdateThresholdRequest Request;
typedef SetZeroAngleUpdateThresholdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetZeroAngleUpdateThreshold
} // namespace ros_mscl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mscl::SetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "ea1115ed39d8a581530c7c251ee443e6";
  }

  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThreshold&) { return value(); }
};

template<>
struct DataType< ::ros_mscl::SetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "ros_mscl/SetZeroAngleUpdateThreshold";
  }

  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThreshold&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mscl::SetZeroAngleUpdateThresholdRequest> should match
// service_traits::MD5Sum< ::ros_mscl::SetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::SetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetZeroAngleUpdateThresholdRequest> should match
// service_traits::DataType< ::ros_mscl::SetZeroAngleUpdateThreshold >
template<>
struct DataType< ::ros_mscl::SetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mscl::SetZeroAngleUpdateThresholdResponse> should match
// service_traits::MD5Sum< ::ros_mscl::SetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::ros_mscl::SetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mscl::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mscl::SetZeroAngleUpdateThresholdResponse> should match
// service_traits::DataType< ::ros_mscl::SetZeroAngleUpdateThreshold >
template<>
struct DataType< ::ros_mscl::SetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mscl::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::ros_mscl::SetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MSCL_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H
